#!/bin/sh

if [ -z "$TEST_PAVICS_SDI_REPO" ]; then
    TEST_PAVICS_SDI_REPO=true
    echo "TEST_PAVICS_SDI_REPO not set, default to '$TEST_PAVICS_SDI_REPO'"
else
    echo "TEST_PAVICS_SDI_REPO has been set to '$TEST_PAVICS_SDI_REPO'"
fi

if [ -z "$PAVICS_SDI_BRANCH" ]; then
    PAVICS_SDI_BRANCH=master
    echo "PAVICS_SDI_BRANCH not set, default to '$PAVICS_SDI_BRANCH'"
else
    echo "PAVICS_SDI_BRANCH has been set to '$PAVICS_SDI_BRANCH'"
fi

if [ -z "$PAVICS_SDI_REPO" ]; then
    PAVICS_SDI_REPO='Ouranosinc/pavics-sdi'
    echo "PAVICS_SDI_REPO not set, default to '$PAVICS_SDI_REPO'"
else
    echo "PAVICS_SDI_REPO has been set to '$PAVICS_SDI_REPO'"
fi

if [ -z "$TEST_FINCH_REPO" ]; then
    TEST_FINCH_REPO=true
    echo "TEST_FINCH_REPO not set, default to '$TEST_FINCH_REPO'"
else
    echo "TEST_FINCH_REPO has been set to '$TEST_FINCH_REPO'"
fi

if [ -z "$FINCH_BRANCH" ]; then
    FINCH_BRANCH=master
    echo "FINCH_BRANCH not set, default to '$FINCH_BRANCH'"
else
    echo "FINCH_BRANCH has been set to '$FINCH_BRANCH'"
fi

if [ -z "$FINCH_REPO" ]; then
    FINCH_REPO='bird-house/finch'
    echo "FINCH_REPO not set, default to '$FINCH_REPO'"
else
    echo "FINCH_REPO has been set to '$FINCH_REPO'"
fi

if [ -z "$TEST_PAVICS_LANDING_REPO" ]; then
    TEST_PAVICS_LANDING_REPO=true
    echo "TEST_PAVICS_LANDING_REPO not set, default to '$TEST_PAVICS_LANDING_REPO'"
else
    echo "TEST_PAVICS_LANDING_REPO has been set to '$TEST_PAVICS_LANDING_REPO'"
fi

if [ -z "$PAVICS_LANDING_BRANCH" ]; then
    PAVICS_LANDING_BRANCH=master
    echo "PAVICS_LANDING_BRANCH not set, default to '$PAVICS_LANDING_BRANCH'"
else
    echo "PAVICS_LANDING_BRANCH has been set to '$PAVICS_LANDING_BRANCH'"
fi

if [ -z "$PAVICS_LANDING_REPO" ]; then
    PAVICS_LANDING_REPO='Ouranosinc/PAVICS-landing'
    echo "PAVICS_LANDING_REPO not set, default to '$PAVICS_LANDING_REPO'"
else
    echo "PAVICS_LANDING_REPO has been set to '$PAVICS_LANDING_REPO'"
fi

if [ -z "$TEST_RAVEN_REPO" ]; then
    TEST_RAVEN_REPO=false
    echo "TEST_RAVEN_REPO not set, default to '$TEST_RAVEN_REPO'"
else
    echo "TEST_RAVEN_REPO has been set to '$TEST_RAVEN_REPO'"
fi

if [ -z "$RAVEN_BRANCH" ]; then
    RAVEN_BRANCH=main
    echo "RAVEN_BRANCH not set, default to '$RAVEN_BRANCH'"
else
    echo "RAVEN_BRANCH has been set to '$RAVEN_BRANCH'"
fi

if [ -z "$RAVEN_REPO" ]; then
    RAVEN_REPO='Ouranosinc/raven'
    echo "RAVEN_REPO not set, default to '$RAVEN_REPO'"
else
    echo "RAVEN_REPO has been set to '$RAVEN_REPO'"
fi

if [ -z "$TEST_RAVENPY_REPO" ]; then
    TEST_RAVENPY_REPO=false
    echo "TEST_RAVENPY_REPO not set, default to '$TEST_RAVENPY_REPO'"
else
    echo "TEST_RAVENPY_REPO has been set to '$TEST_RAVENPY_REPO'"
fi

if [ -z "$RAVENPY_BRANCH" ]; then
    RAVENPY_BRANCH=master
    echo "RAVENPY_BRANCH not set, default to '$RAVENPY_BRANCH'"
else
    echo "RAVENPY_BRANCH has been set to '$RAVENPY_BRANCH'"
fi

if [ -z "$RAVENPY_REPO" ]; then
    RAVENPY_REPO='CSHS-CWRA/RavenPy'
    echo "RAVENPY_REPO not set, default to '$RAVENPY_REPO'"
else
    echo "RAVENPY_REPO has been set to '$RAVENPY_REPO'"
fi

if [ -z "$TEST_ESGF_COMPUTE_API_REPO" ]; then
    TEST_ESGF_COMPUTE_API_REPO=false
    echo "TEST_ESGF_COMPUTE_API_REPO not set, default to '$TEST_ESGF_COMPUTE_API_REPO'"
else
    echo "TEST_ESGF_COMPUTE_API_REPO has been set to '$TEST_ESGF_COMPUTE_API_REPO'"
fi

if [ -z "$ESGF_COMPUTE_API_BRANCH" ]; then
    ESGF_COMPUTE_API_BRANCH=devel
    echo "ESGF_COMPUTE_API_BRANCH not set, default to '$ESGF_COMPUTE_API_BRANCH'"
else
    echo "ESGF_COMPUTE_API_BRANCH has been set to '$ESGF_COMPUTE_API_BRANCH'"
fi

if [ -z "$ESGF_COMPUTE_API_REPO" ]; then
    ESGF_COMPUTE_API_REPO='ESGF/esgf-compute-api'
    echo "ESGF_COMPUTE_API_REPO not set, default to '$ESGF_COMPUTE_API_REPO'"
else
    echo "ESGF_COMPUTE_API_REPO has been set to '$ESGF_COMPUTE_API_REPO'"
fi

if [ -z "$TEST_LOCAL_NOTEBOOKS" ]; then
    TEST_LOCAL_NOTEBOOKS=true
    echo "TEST_LOCAL_NOTEBOOKS not set, default to '$TEST_LOCAL_NOTEBOOKS'"
else
    echo "TEST_LOCAL_NOTEBOOKS has been set to '$TEST_LOCAL_NOTEBOOKS'"
fi
