# For testing quickly without having to do a full rebuild.

FROM pavics/workflow-tests:py310-231107-update240130

#ENV ESMFMKFILE="/opt/conda/envs/birdy/lib/esmf.mk"

#ENV PROJ_DATA="/opt/conda/envs/birdy/share/proj"

USER root

# Use 'update' for existing and 'install' for new package.
# Keep same channel ordering to not revert anything.
RUN umask 0000 \
    && mamba install -c conda-forge -c cdat -c bokeh -c plotly -c pyviz/label/dev -c defaults -n birdy xscen==0.8.2 ravenpy==0.13.0 pydantic==2.6.3 \
    && mamba clean --all --yes \
    && pip install --no-cache-dir --upgrade finagos
#    && pip uninstall -y ravenpy \
#    && mamba install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy ravenpy aiohttp

#RUN umask 0000 \
#    && python -m pip install --upgrade --force-reinstall --no-deps --no-cache-dir netcdf4==1.6.0 --no-binary netcdf4
# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive apt-get install -y unzip && \
#     apt-get clean && \
#     mkdir /notebook_dir && \
#     chown jenkins /notebook_dir

#RUN umask 0000 \
#    && pip install https://github.com/CSHS-CWRA/RavenPy/archive/refs/heads/master.zip

USER jenkins
