FROM pavics/workflow-tests:210216

USER root

RUN umask 0000 \
    && conda update -c zeitsperre -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy clisops xclim \
    && conda install -c zeitsperre -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy ravenpy

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y fonts-humor-sans && \
    apt-get clean

USER jenkins
