# For testing quickly without having to do a full rebuild.

FROM pavics/workflow-tests:210527.1

USER root

# Use 'update' for existing and 'install' for new package.
# Keep same channel ordering to not revert anything.
#RUN umask 0000 \
#    && conda update -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy clisops xclim \
#    && pip uninstall -y ravenpy \
#    && conda install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy ravenpy aiohttp

RUN umask 0000 \
    && conda update -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy xclim \
    && conda install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy intake intake-esm gcsfs zarr

#RUN umask 0000 \
#    && pip install https://github.com/CSHS-CWRA/RavenPy/archive/refs/heads/master.zip

USER jenkins
